directories:
  output: ./exeResult/
  buildResources: ./resources/installer/
  app: .
productName: test
appId: com.electron.hello
asar: true
protocols:
  name: test
  schemes:
    - test
win:
  target:
    - zip
    - nsis
  icon: ./resources/installer/Icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
files: []
electronVersion: 17.1.0
